# Generated by Django 4.2.7 on 2023-11-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProducto', models.CharField(max_length=50)),
                ('desProducto', models.CharField(max_length=200)),
                ('catProducto', models.CharField(max_length=20)),
                ('canProducto', models.PositiveIntegerField(default=True)),
                ('precioProducto', models.PositiveBigIntegerField(default=True)),
                ('estProducto', models.BooleanField(default=True)),
            ],
        ),
    ]
