# Generated by Django 4.2.7 on 2023-12-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorias_clientes_factura_proveedores_ventas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.AddField(
            model_name='ventas',
            name='producto',
            field=models.ManyToManyField(to='api.productos'),
        ),
    ]
