# Generated by Django 4.2.7 on 2023-12-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ventas_producto_ventas_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ManyToManyField(to='api.clientes'),
        ),
    ]
