# Generated by Django 4.2.7 on 2023-12-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_factura_cliente_factura_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='productos',
            name='canProducto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='catProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorias'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioProducto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=98707987987, on_delete=django.db.models.deletion.CASCADE, to='api.clientes'),
            preserve_default=False,
        ),
    ]
