# Generated by Django 4.2.7 on 2023-12-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productos_catproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ManyToManyField(to='api.productos'),
        ),
    ]
