# Generated by Django 4.2.7 on 2023-12-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_factura_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
