# Generated by Django 4.2.7 on 2023-12-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_producto_factura_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precioProducto',
            field=models.PositiveIntegerField(),
        ),
    ]
