# Generated by Django 4.2.7 on 2023-12-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_productos_precioproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precioProducto',
            field=models.PositiveIntegerField(default=True),
        ),
    ]
