# Generated by Django 4.2.7 on 2023-12-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_productos_precioproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
    ]
