# Generated by Django 4.2.7 on 2023-12-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='precio_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioProducto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
